//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lrt_Ilukste
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoefTank
    {
        public int CoefTankID { get; set; }
        public Nullable<short> TankID { get; set; }
        public Nullable<short> Zone { get; set; }
        public Nullable<double> H_Level { get; set; }
        public Nullable<double> V_Base { get; set; }
    }
}
