//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lrt_Ilukste
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoefDensity
    {
        public int CoefDensityID { get; set; }
        public Nullable<float> p_min { get; set; }
        public Nullable<float> p_max { get; set; }
        public Nullable<double> b { get; set; }
    }
}
