//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lrt_Ilukste
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationRegister()
        {
            this.OperationData = new HashSet<OperationData>();
        }
    
        public int RegID { get; set; }
        public Nullable<System.DateTime> StartDataTime { get; set; }
        public Nullable<System.DateTime> EndDataTime { get; set; }
        public Nullable<int> OperID { get; set; }
        public Nullable<int> ProvID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> ActN { get; set; }
        public Nullable<System.DateTime> CreateDataTime { get; set; }
        public Nullable<bool> FullReport { get; set; }
        public Nullable<int> TankID { get; set; }
    
        public virtual OperationName OperationName { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual Persons Persons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationData> OperationData { get; set; }
        public virtual Tanks Tanks { get; set; }
    }
}
