//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lrt_Ilukste
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaabCalculations
    {
        public int SaabCalcID { get; set; }
        public Nullable<int> SaabID { get; set; }
        public Nullable<float> AirTemp { get; set; }
        public Nullable<float> CalcVolume { get; set; }
        public Nullable<float> CalcDensity20 { get; set; }
        public Nullable<float> CalcVolume20 { get; set; }
        public Nullable<float> CalcMassa { get; set; }
    }
}
