//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lrt_Ilukste
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaabData
    {
        public int SaabID { get; set; }
        public Nullable<int> TankID { get; set; }
        public Nullable<System.DateTime> SaabDateTime { get; set; }
        public Nullable<float> TankLevel { get; set; }
        public Nullable<float> TankAvgTemp { get; set; }
        public Nullable<float> TankDensity { get; set; }
        public Nullable<float> TankVolume { get; set; }
        public Nullable<float> TankMassa { get; set; }
 
    }
}
