//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lrt_Ilukste
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneTank
    {
        public int ZoneTankID { get; set; }
        public Nullable<byte> TankID { get; set; }
        public Nullable<byte> Zone { get; set; }
        public Nullable<short> HA_Level { get; set; }
        public Nullable<double> VA_Base { get; set; }
    }
}
